import Foundation

@MainActor
class AppDependencies {

    // Development token generated by the local Rails API script.
    // TODO: Replace this with a proper login flow and secure token storage.
    static let apiBearerToken: String? = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.mkVKHybKh9mH9Xo7Grpigvxrm5tdVJwp26faGBVg_KA"

    // MARK: - Services
    static let itemService: ItemServiceProtocol = ItemAPIService()

    static let friendService: FriendServiceProtocol = FriendAPIService()

    static let loanService: LoanServiceProtocol = LoanAPIService()
}
