import Foundation

@MainActor
class AppDependencies {

    // MARK: - Feature flag
    // Use real API services for local backend integration.
    static let useMockServices: Bool = false

    // Development token generated by the local Rails API script.
    // TODO: Replace this with a proper login flow and secure token storage.
    static let apiBearerToken: String? = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.mkVKHybKh9mH9Xo7Grpigvxrm5tdVJwp26faGBVg_KA"

    // MARK: - Services
    static let itemService: ItemServiceProtocol = useMockServices
        ? MockItemService()
        : ItemAPIService()

    static let friendService: FriendServiceProtocol = useMockServices
        ? MockFriendService()
        : FriendAPIService()

    static let loanService: LoanServiceProtocol = useMockServices
        ? MockLoanService()
        : LoanAPIService()
}
